title: "Tobias's blog"

description: >-
  A blog from tobiasjc

who: >-
  Backend developer focused on algorithm optmization,
  big data, data processing and database management.
  I take other studying fields as a hobby. (:

url: "https://tobiasjc.github.io"
github: tobiasjc
linkedin: tobiasjc
email: tobias.jc07@gmail.com

paginate: 5
paginate_path: "/blog/page:num/"

plugin:
  - jekyll-feed
  - jekyll-paginate
